== Craft the authorization header

All requests must be authorized using the login credentials of a valid user.

Join your username and password with a colon `:` and base64-encode the resulting string.

[source, bash]
----
base64({neo4j-username}:{neo4j-password})
----

Prepend `Basic` to the output, and provide the entire string as value to an `Authorization` header.

[source, bash]
----
Authorization: Basic bmVvNGo6dmVyeXNlY3JldA==
----

link:https://neo4j.com/docs/query-api/current/authentication-authorization/[More info on authorizing requests]


== Create an example graph

Run Cypher queries by submitting `POST` requests to your instance's Query API endpoint.
Do not hardcode or concatenate parameters: use placeholders and specify the parameters via the `parameters` object in the body.
Line breaks in queries are not supported.

[source, headers, copy=true]
----
POST {neo4j-server-uri}/db/{neo4j-database-name}/query/v2
Authorization: Basic base64({neo4j-username}:{neo4j-password})
Content-Type: application/json
----

.Create two `Person` nodes and a `KNOWS` relationship between them
[source, json, copy=true]
----
{
  "statement": "CREATE (a:Person {name: $name}) CREATE (b:Person {name: $friendName}) CREATE (a)-[:KNOWS]->(b)",
  "parameters": {
    "name": "Alice",
    "friendName": "David"
  }
}
----

link:https://neo4j.com/docs/query-api/current/query/[More info on executing queries]


== Query a graph

To retrieve information from the database, use the Cypher clause `MATCH`.

[source, headers, copy=true]
----
POST {neo4j-server-uri}/db/{neo4j-database-name}/query/v2
Authorization: Basic base64({neo4j-username}:{neo4j-password})
Content-Type: application/json
----

.Retrieve all `Person` nodes who know other persons
[source, json, copy=true]
----
{
  "statement": "MATCH (p:Person)-[:KNOWS]->(:Person) RETURN p.name AS name",
  "parameters": {}
}
----

link:https://neo4j.com/docs/query-api/current/query/[More info on executing queries]
